security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
      entry_point: App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        target: homepage
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS } # Ajoutez cette ligne pour la page d'inscription
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/pdf, roles: ROLE_USER }
    - { path: ^/generate-pdf, roles: ROLE_USER }
    - { path: ^/history, roles: ROLE_USER }
    - { path: ^/subscription, roles: ROLE_USER }